version: '3.8'

services:

  web:
    build: .
    image: 'websource'
    command: bash -c "cd news_scorer && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./news_scorer/env/.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./news_scorer/env/.env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  celery_worker:
    build:
      context: .
    image: 'websource'
    env_file:
      - ./news_scorer/env/.env
    command: bash -c "cd news_scorer && python -m celery -A news_grabber worker -l info -P prefork -Q normal"
    volumes_from:
      - web
    depends_on:
      - web

  celery_worker_tf:
    build:
      context: .
    image: 'websource'
    env_file:
      - ./news_scorer/env/.env
    command: bash -c "cd news_scorer && python -m celery -A news_grabber worker -l info -P prefork -n tf_worker -Q tf"
    volumes_from:
      - web
    depends_on:
      - web

  celery_beat:
    build:
      context: .
    image: 'websource'
    env_file:
      - ./news_scorer/env/.env
    command: bash -c "cd news_scorer && python -m celery -A news_grabber beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes_from:
      - web
    depends_on:
      - web


volumes:
  postgres_data:
  redisdata: