# Generated by Django 3.2.7 on 2021-09-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='is_integrate_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NewsStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('body', models.TextField(null=True)),
                ('source_url', models.URLField(unique=True)),
                ('remark', models.TextField(null=True)),
                ('news_datetime', models.DateTimeField(null=True)),
                ('execution_batch', models.CharField(max_length=256, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_store.newssource')),
            ],
        ),
    ]
