# Generated by Django 3.2.7 on 2021-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0004_newssource_source_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstore',
            name='source_url',
        ),
        migrations.AddField(
            model_name='newsstore',
            name='news_url',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
