# Generated by Django 3.2.7 on 2021-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0008_alter_newsstore_sentiment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentsource',
            old_name='model_name',
            new_name='pretrain_model_name',
        ),
        migrations.AddField(
            model_name='sentimentsource',
            name='token_model_name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
