# Generated by Django 3.2.7 on 2021-10-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0012_newssource_excluded_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentsource',
            old_name='model_path',
            new_name='pretrain_model_config_path',
        ),
        migrations.RemoveField(
            model_name='sentimentsource',
            name='pretrain_model_name',
        ),
        migrations.AddField(
            model_name='sentimentsource',
            name='pretrain_model_path',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sentimentsource',
            name='weight_path',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
