# Generated by Django 3.2.7 on 2021-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0015_newsstore_enable_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstore',
            name='enable_tag',
        ),
        migrations.RemoveField(
            model_name='newsstore',
            name='news_source_tag',
        ),
        migrations.AddField(
            model_name='newssource',
            name='enable_tag',
            field=models.BooleanField(default=False),
        ),
    ]
