# Generated by Django 3.2.7 on 2021-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=256, unique=True)),
                ('source_url', models.URLField()),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
