# Generated by Django 3.2.7 on 2021-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0002_auto_20210908_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='execution_batch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='news_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
