# Generated by Django 3.2.7 on 2021-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0003_auto_20210908_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='source_timezone',
            field=models.CharField(default='US/Eastern', max_length=256),
        ),
    ]
