# Generated by Django 3.2.7 on 2021-09-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0005_auto_20210910_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=256, unique=True)),
                ('model_name', models.CharField(default=None, max_length=256, null=True)),
                ('config_path', models.CharField(default=None, max_length=512, null=True)),
                ('model_path', models.CharField(default=None, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsstore',
            name='actual_news_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_source', to='news_store.newssource'),
        ),
        migrations.AlterField(
            model_name='newsstore',
            name='news_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parser_source', to='news_store.newssource'),
        ),
        migrations.CreateModel(
            name='SentimentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_result', models.IntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('news_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_store.newsstore')),
                ('sentiment_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_store.sentimentsource')),
            ],
        ),
        migrations.AddField(
            model_name='newsstore',
            name='sentiment_data',
            field=models.ManyToManyField(to='news_store.SentimentStore'),
        ),
    ]
