# Generated by Django 3.2.7 on 2021-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0006_auto_20210910_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='parent_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
