# Generated by Django 3.2.7 on 2021-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0011_remove_newsstore_sentiment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='excluded_source',
            field=models.ManyToManyField(blank=True, to='news_store.NewsSource'),
        ),
    ]
