# Generated by Django 3.2.7 on 2021-10-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0013_auto_20211009_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_store.newssource')),
            ],
        ),
        migrations.AddField(
            model_name='newsstore',
            name='news_source_tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_tag', to='news_store.newssourcetag'),
        ),
    ]
