# Generated by Django 3.2.7 on 2021-10-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0014_auto_20211013_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstore',
            name='enable_tag',
            field=models.BooleanField(default=False),
        ),
    ]
