# Generated by Django 3.2.7 on 2021-10-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0017_auto_20211013_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssourcetag',
            name='news_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_store.newssource'),
        ),
        migrations.AlterField(
            model_name='newssourcetag',
            name='tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name='newssourcetag',
            constraint=models.UniqueConstraint(fields=('tag', 'news_source'), name='unique_tag_news_source'),
        ),
    ]
