# Generated by Django 3.2.7 on 2022-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_store', '0019_newsstore_news_source_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentsource',
            name='pretrain_model_config_path',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentsource',
            name='pretrain_model_path',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
